In [1]:
import numpy as np
import keras 
import tensorflow as tf

Using TensorFlow backend.


In [2]:
dataset = keras.datasets.imdb.load_data()

In [3]:
word_indexes = keras.datasets.imdb.get_word_index()

In [4]:
word_indexes

{'official': 4116,
 'ayesh': 87416,
 'brokerage': 56521,
 'implant': 23559,
 'enhancements': 26406,
 "majorettes'": 55392,
 '25th': 21206,
 'easton': 58858,
 'advantage': 3076,
 'encrusted': 41561,
 'injects': 14035,
 'ropsenlski': 55752,
 'longed': 18368,
 "'personalities'": 81034,
 "''empire": 52876,
 'innercity': 57840,
 'dyson': 30751,
 'sagamore': 57168,
 'passionately': 13540,
 'caravans': 77556,
 'kendis': 73774,
 'aidsssss': 56849,
 "rhimes'": 65087,
 'preprint': 60768,
 'bossman': 35652,
 'threlkis': 73431,
 'orangutans': 46177,
 'paradoxes': 25258,
 'sweeny': 29343,
 'amerterish': 52368,
 'grubach': 66487,
 'bass': 9467,
 'chauncey': 65187,
 'kryukova': 87643,
 'mainstay': 19099,
 'extremis': 38364,
 'divergent': 36022,
 "hinckley's": 57057,
 'unfaithful': 10986,
 'babaji': 73121,
 'schmaltzy': 16062,
 'securing': 19226,
 'ashley': 4918,
 "'magic": 65214,
 'resignedly': 85770,
 'mortitz': 53975,
 'manjit': 52550,
 'encapsulations': 59868,
 'enervated': 49220,
 'quashes': 7439

In [5]:
index_to_word = {}
for key,val in word_indexes.items():
    index_to_word[val] = key
(x_train,y_train),(x_test,y_test) = dataset

In [6]:
def get_line(index):
    return ' '.join([index_to_word[word] for word in x_train[index]])
print(get_line(0),y_train[0])
print(get_line(1),y_train[1])
print(get_line(2),y_train[2])
#print(get_line(18152),y_train[18152])


the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of gilmore's br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but whe

In [7]:
#above seems like a bit cleaned dataset to use...
## also x data is quite like embedded dataset earlier 

In [8]:
word_count = lambda sentence : len(sentence) 
longest_seq = max(x_train,key=word_count) 
longest_seq_length = len(longest_seq)
print(longest_seq,longest_seq_length)

[1, 1014, 300, 4349, 768, 2702, 1014, 11641, 1538, 5, 3483, 5934, 1918, 1812, 14326, 5, 1378, 9125, 11641, 1538, 5, 3483, 5934, 645, 183, 125, 19, 6, 4349, 768, 2702, 1014, 429, 1812, 14326, 5, 1378, 9125, 1793, 8, 4, 2269, 7, 4, 1014, 199, 9149, 28, 8, 140, 143, 8915, 11, 661, 8, 79, 4, 1176, 9125, 5, 14326, 13328, 56, 402, 23, 34, 656, 505, 21398, 86, 3483, 5, 95, 11641, 1538, 6, 1124, 38605, 34, 9125, 8, 11641, 562, 4, 1933, 46, 7, 4, 5934, 597, 3483, 805, 8, 339, 27, 597, 21, 4, 16980, 6075, 90, 137, 9125, 5, 14326, 64231, 56, 23, 90, 11, 4, 3130, 19, 9125, 15011, 245, 23, 11641, 14326, 270, 56, 6, 2702, 1005, 3483, 14385, 83, 4, 1746, 5, 57986, 120, 4, 350, 5836, 1646, 14326, 23, 4, 1005, 103, 9026, 5, 656, 459, 7, 3483, 14326, 9491, 6, 2702, 83, 4, 1746, 5, 1678, 4, 10510, 270, 12, 56, 4, 18840, 95, 270, 56, 18, 6, 1405, 31929, 39, 4, 655, 5836, 63, 62, 28, 276, 11641, 143, 4, 2702, 21, 3483, 5290, 4, 2702, 120, 208, 159, 27, 597, 385, 6668, 180, 14326, 5, 9125, 27768, 160, 2702,

In [9]:
longest_seq_length=100#keeping max longest seq length to 100
padded_seq = keras.preprocessing.sequence.pad_sequences(x_train,longest_seq_length,padding="post")
print(padded_seq)


[[ 1415    33     6 ...    19   178    32]
 [  163    11  3215 ...    16   145    95]
 [ 1301     4  1873 ...     7   129   113]
 ...
 [   11     6  4065 ...     4  3586 22459]
 [  100  2198     8 ...    12     9    23]
 [   78  1099    17 ...   204   131     9]]


In [10]:
vocab_length = len(index_to_word)+1

print(len(index_to_word),index_to_word[88584],word_indexes["'l'"])


88584 'l' 88584


In [11]:
model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_length+2,100,input_length=longest_seq_length))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1,activation='sigmoid'))
model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 100)          8858700   
_________________________________________________________________
flatten_1 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 10001     
Total params: 8,868,701
Trainable params: 8,868,701
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [13]:
np.max(padded_seq)
np.argwhere(padded_seq==np.max(padded_seq))



array([[18152,    16]])

In [14]:
padded_seq[18152]

array([    4,   236,   747,   234,    42,    38,    59,   272,    53,
       23782,    74,    32,     4,  2281, 66239,  1655, 88586,     5,
         488, 24672,  2505,    50,    26,   450,  1307,  8887,   105,
          37,    26,  1038,     6,   117,  8027,     5,  8138,    39,
          68,   986,    40, 73963, 38433,    17,     4,  9426, 33367,
        1750, 13258, 17330,    17,     4,   948, 24588,     5,  3753,
        6104,    17,     4, 18258,  8082,     8,     4, 12852,   313,
          50,    26,     6,   378,     7,  1238,  2943,   139,     5,
         388,     7,  2038,  1465,     8,   358,    18,     4,  1758,
       21394,  9523,   793,   178,    21,   572,     4,   270,  1328,
           5,  2298,  4627,    60,  2305,    18,    35,   735,    26,
        2877], dtype=int32)

In [15]:
print(x_train.shape)
start_seq = 15000
end_seq = 19000
padded_seq_data = padded_seq[start_seq:end_seq] 
y_train_data = y_train[start_seq:end_seq]
model.fit(padded_seq_data,y_train_data,epochs=1,verbose=1)


(25000,)
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
4000/4000 [==============================] - 10s 2ms/step - loss: 0.6847 - accuracy: 0.5782


In [16]:
model.fit(padded_seq,y_train,epochs=10,verbose=1,batch_size=500,shuffle=False)

Epoch 1/10
25000/25000 [==============================] - 4s 176us/step - loss: 0.6052 - accuracy: 0.7728
Epoch 2/10
25000/25000 [==============================] - 4s 175us/step - loss: 0.4573 - accuracy: 0.8580
Epoch 3/10
25000/25000 [==============================] - 4s 180us/step - loss: 0.3166 - accuracy: 0.9085
Epoch 4/10
25000/25000 [==============================] - 4s 170us/step - loss: 0.2255 - accuracy: 0.9405
Epoch 5/10
25000/25000 [==============================] - 4s 172us/step - loss: 0.1656 - accuracy: 0.9629
Epoch 6/10
25000/25000 [==============================] - 4s 172us/step - loss: 0.1231 - accuracy: 0.9768
Epoch 7/10
25000/25000 [==============================] - 4s 173us/step - loss: 0.0922 - accuracy: 0.9863
Epoch 8/10
25000/25000 [==============================] - 4s 178us/step - loss: 0.0697 - accuracy: 0.9921
Epoch 9/10
25000/25000 [==============================] - 4s 173us/step - loss: 0.0532 - accuracy: 0.9956
Epoch 10/10
25000/25000 [=====================

In [17]:
#prediction 
padded_test_seq = keras.preprocessing.sequence.pad_sequences(x_test,longest_seq_length,padding="post")
test_score = model.evaluate(padded_test_seq,y_test)
print(test_score)

25000/25000 [==============================] - 0s 17us/step
[0.33706461216926575, 0.8547999858856201]
