In [1]:
import numpy as np
import keras 
import tensorflow as tf

Using TensorFlow backend.


In [2]:
# Let's try first with following simplest set of data which are dummy movie 
# review comments and clasification whether its a good movie or not
# taken from https://stackabuse.com/python-for-nlp-word-embeddings-for-deep-learning-in-keras/

corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]


In [3]:
sentiments = np.array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])


In [4]:
word_tokenizer = keras.preprocessing.text.Tokenizer()
word_tokenizer.fit_on_texts(corpus)

In [5]:
vocab_length = len(word_tokenizer.word_index) + 1

In [6]:
vocab_length

44

In [7]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)

In [8]:
embedded_sentences

[[14, 3, 15, 16, 1],
 [4, 17, 6, 9, 5, 7, 2],
 [18, 19, 20, 2, 3, 21],
 [22, 23],
 [24, 25, 26, 27, 5, 7, 2],
 [28, 8, 9, 29],
 [30, 31, 32, 8, 33, 1],
 [2, 3, 8, 34, 1],
 [10, 11],
 [35, 36, 37],
 [12, 38],
 [2, 6, 39, 40],
 [5, 41, 13, 7, 4, 1],
 [4, 1, 6, 10],
 [5, 42, 13, 43],
 [4, 11, 3, 12]]

In [9]:
len(embedded_sentences[0])


5

In [10]:
# Now let's find out what's max length sentence
maxiumum = 0
word_count = lambda sentence : len(sentence) 

longest_seq = max(embedded_sentences,key=word_count) 
longest_seq_length = len(longest_seq)
print(longest_seq,longest_seq_length)

[4, 17, 6, 9, 5, 7, 2] 7


In [11]:
pad_sequences = keras.preprocessing.sequence.pad_sequences
padded_seq = pad_sequences(embedded_sentences,longest_seq_length,padding="post")
print(padded_seq)

[[14  3 15 16  1  0  0]
 [ 4 17  6  9  5  7  2]
 [18 19 20  2  3 21  0]
 [22 23  0  0  0  0  0]
 [24 25 26 27  5  7  2]
 [28  8  9 29  0  0  0]
 [30 31 32  8 33  1  0]
 [ 2  3  8 34  1  0  0]
 [10 11  0  0  0  0  0]
 [35 36 37  0  0  0  0]
 [12 38  0  0  0  0  0]
 [ 2  6 39 40  0  0  0]
 [ 5 41 13  7  4  1  0]
 [ 4  1  6 10  0  0  0]
 [ 5 42 13 43  0  0  0]
 [ 4 11  3 12  0  0  0]]


In [12]:
#Now X data is ready to use ... let's one hot encode Y data
#y = keras.utils.to_categorical(sentiments)
#print(y)

In [13]:
model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_length,20,input_length=longest_seq_length))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1,activation='sigmoid'))
model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 20)             880       
_________________________________________________________________
flatten_1 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 141       
Total params: 1,021
Trainable params: 1,021
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [15]:
model.fit(padded_seq,sentiments,epochs=100,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
16/16 [==============================] - 0s 9ms/step - loss: 0.7037 - accuracy: 0.3125
Epoch 2/100
16/16 [==============================] - 0s 95us/step - loss: 0.6996 - accuracy: 0.4375
Epoch 3/100
16/16 [==============================] - 0s 87us/step - loss: 0.6955 - accuracy: 0.4375
Epoch 4/100
16/16 [==============================] - 0s 100us/step - loss: 0.6915 - accuracy: 0.5625
Epoch 5/100
16/16 [==============================] - 0s 101us/step - loss: 0.6875 - accuracy: 0.6250
Epoch 6/100
16/16 [==============================] - 0s 121us/step - loss: 0.6835 - accuracy: 0.6250
Epoch 7/100
16/16 [==============================] - 0s 87us/step - loss: 0.6795 - accuracy: 0.6875
Epoch 8/100
16/16 [==============================] - 0s 77us/step - loss: 0.6756 - accuracy: 0.7500
Epoch 9/100
16/16 [==============================] - 0s 96us/step - loss: 0.6716 - accuracy: 0.9375
Epoch 10/100
16/16 [==============================

Epoch 80/100
16/16 [==============================] - 0s 97us/step - loss: 0.3192 - accuracy: 1.0000
Epoch 81/100
16/16 [==============================] - 0s 103us/step - loss: 0.3143 - accuracy: 1.0000
Epoch 82/100
16/16 [==============================] - 0s 83us/step - loss: 0.3094 - accuracy: 1.0000
Epoch 83/100
16/16 [==============================] - 0s 80us/step - loss: 0.3046 - accuracy: 1.0000
Epoch 84/100
16/16 [==============================] - 0s 126us/step - loss: 0.2998 - accuracy: 1.0000
Epoch 85/100
16/16 [==============================] - 0s 85us/step - loss: 0.2951 - accuracy: 1.0000
Epoch 86/100
16/16 [==============================] - 0s 103us/step - loss: 0.2904 - accuracy: 1.0000
Epoch 87/100
16/16 [==============================] - 0s 90us/step - loss: 0.2858 - accuracy: 1.0000
Epoch 88/100
16/16 [==============================] - 0s 92us/step - loss: 0.2812 - accuracy: 1.0000
Epoch 89/100
16/16 [==============================] - 0s 89us/step - loss: 0.2768 - accu

In [16]:
#prediction 
instance = ["It was very boring",'excellent movie','This is an excellent movie']
instance = word_tokenizer.texts_to_sequences(instance)
print(instance)
instance = pad_sequences(instance, padding='post', maxlen=longest_seq_length)
print(model.predict(instance))

[[2, 6, 39, 40], [16, 1], [14, 3, 15, 16, 1]]
[[0.16297159]
 [0.36877173]
 [0.8352111 ]]


In [17]:
### Now Let's extend above example and test with actual movie sentiment dataset
dataset = keras.datasets.imdb.load_data()