In [1]:
import numpy as np
import keras 
import tensorflow as tf

Using TensorFlow backend.


In [2]:
# Let's try first with following simplest set of data which are dummy movie 
# review comments and clasification whether its a good movie or not
# taken from https://stackabuse.com/python-for-nlp-word-embeddings-for-deep-learning-in-keras/

corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic',
    
    # average Reviews

    "it is ok",
    'one time watch',
    'ok ok types',
    'can watch one time',
    'not too great'

]


In [3]:
sentiments = np.array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,2,2,2,2,2])


In [4]:
word_tokenizer = keras.preprocessing.text.Tokenizer()
word_tokenizer.fit_on_texts(corpus)

In [5]:
vocab_length = len(word_tokenizer.word_index) + 1

In [6]:
vocab_length

51

In [7]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)

In [8]:
embedded_sentences

[[18, 2, 19, 20, 3],
 [4, 21, 6, 12, 5, 7, 1],
 [22, 23, 8, 1, 2, 24],
 [25, 26],
 [27, 28, 29, 30, 5, 7, 1],
 [31, 9, 12, 32],
 [33, 34, 35, 9, 36, 3],
 [1, 2, 9, 37, 3],
 [13, 14],
 [38, 39, 40],
 [15, 41],
 [1, 6, 42, 43],
 [5, 44, 10, 7, 4, 3],
 [4, 3, 6, 13],
 [5, 45, 10, 46],
 [4, 14, 2, 15],
 [1, 2, 11],
 [16, 17, 8],
 [11, 11, 47],
 [48, 8, 16, 17],
 [10, 49, 50]]

In [9]:
len(embedded_sentences[0])


5

In [10]:
# Now let's find out what's max length sentence
maxiumum = 0
word_count = lambda sentence : len(sentence) 

longest_seq = max(embedded_sentences,key=word_count) 
longest_seq_length = len(longest_seq)
print(longest_seq,longest_seq_length)

[4, 21, 6, 12, 5, 7, 1] 7


In [11]:
pad_sequences = keras.preprocessing.sequence.pad_sequences
padded_seq = pad_sequences(embedded_sentences,longest_seq_length,padding="post")
print(padded_seq)

[[18  2 19 20  3  0  0]
 [ 4 21  6 12  5  7  1]
 [22 23  8  1  2 24  0]
 [25 26  0  0  0  0  0]
 [27 28 29 30  5  7  1]
 [31  9 12 32  0  0  0]
 [33 34 35  9 36  3  0]
 [ 1  2  9 37  3  0  0]
 [13 14  0  0  0  0  0]
 [38 39 40  0  0  0  0]
 [15 41  0  0  0  0  0]
 [ 1  6 42 43  0  0  0]
 [ 5 44 10  7  4  3  0]
 [ 4  3  6 13  0  0  0]
 [ 5 45 10 46  0  0  0]
 [ 4 14  2 15  0  0  0]
 [ 1  2 11  0  0  0  0]
 [16 17  8  0  0  0  0]
 [11 11 47  0  0  0  0]
 [48  8 16 17  0  0  0]
 [10 49 50  0  0  0  0]]


In [13]:
#Now X data is ready to use ... let's one hot encode Y data
y = keras.utils.to_categorical(sentiments)
print(y)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [14]:
model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_length,20,input_length=longest_seq_length))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3,activation='sigmoid'))
model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 20)             1020      
_________________________________________________________________
flatten_1 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 423       
Total params: 1,443
Trainable params: 1,443
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [17]:
model.fit(padded_seq,y,epochs=100,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6896 - accuracy: 0.6032
Epoch 2/100
21/21 [==============================] - 0s 74us/step - loss: 0.6868 - accuracy: 0.6984
Epoch 3/100
21/21 [==============================] - 0s 69us/step - loss: 0.6840 - accuracy: 0.7143
Epoch 4/100
21/21 [==============================] - 0s 73us/step - loss: 0.6811 - accuracy: 0.7302
Epoch 5/100
21/21 [==============================] - 0s 78us/step - loss: 0.6783 - accuracy: 0.7619
Epoch 6/100
21/21 [==============================] - 0s 71us/step - loss: 0.6755 - accuracy: 0.8095
Epoch 7/100
21/21 [==============================] - 0s 66us/step - loss: 0.6727 - accuracy: 0.8413
Epoch 8/100
21/21 [==============================] - 0s 67us/step - loss: 0.6699 - accuracy: 0.8571
Epoch 9/100
21/21 [==============================] - 0s 63us/step - loss: 0.6670 - accuracy: 0.8889
Epoch 10/100
21/21 [==============================] -

Epoch 80/100
21/21 [==============================] - 0s 77us/step - loss: 0.4101 - accuracy: 0.9683
Epoch 81/100
21/21 [==============================] - 0s 74us/step - loss: 0.4060 - accuracy: 0.9683
Epoch 82/100
21/21 [==============================] - 0s 65us/step - loss: 0.4019 - accuracy: 0.9683
Epoch 83/100
21/21 [==============================] - 0s 90us/step - loss: 0.3978 - accuracy: 0.9683
Epoch 84/100
21/21 [==============================] - 0s 68us/step - loss: 0.3937 - accuracy: 0.9683
Epoch 85/100
21/21 [==============================] - 0s 86us/step - loss: 0.3897 - accuracy: 0.9683
Epoch 86/100
21/21 [==============================] - 0s 84us/step - loss: 0.3856 - accuracy: 0.9683
Epoch 87/100
21/21 [==============================] - 0s 94us/step - loss: 0.3816 - accuracy: 0.9683
Epoch 88/100
21/21 [==============================] - 0s 74us/step - loss: 0.3776 - accuracy: 0.9683
Epoch 89/100
21/21 [==============================] - 0s 75us/step - loss: 0.3736 - accurac

In [27]:
#prediction 
instance = ["It was very boring",'excellent movie','This is an excellent movie','ok ok movie']
instance = word_tokenizer.texts_to_sequences(instance)
print(instance)
instance = pad_sequences(instance, padding='post', maxlen=longest_seq_length)
y_pred = model.predict(instance)
print(y_pred)
for x in y_pred:
    print(x)
    print(np.argmax(x))


[[1, 6, 42, 43], [20, 3], [18, 2, 19, 20, 3], [11, 11, 3]]
[[0.70264834 0.22311184 0.2455397 ]
 [0.46696186 0.2636264  0.3039347 ]
 [0.20981568 0.71370476 0.21754959]
 [0.37569633 0.23620367 0.5102246 ]]
[0.70264834 0.22311184 0.2455397 ]
0
[0.46696186 0.2636264  0.3039347 ]
0
[0.20981568 0.71370476 0.21754959]
1
[0.37569633 0.23620367 0.5102246 ]
2


In [28]:
### Now Let's extend above example and test with actual reuters  dataset
dataset = keras.datasets.reuters.load_data()

In [30]:
(x_train,y_train),(x_test,y_test) = dataset

In [31]:
print(x_train.shape, y_train.shape, x_test.shape)

(8982,) (8982,) (2246,)


In [32]:
word_indexes = keras.datasets.reuters.get_word_index()

In [33]:
index_to_word = {}
for key,val in word_indexes.items():
    index_to_word[val] = key


In [34]:
def get_line(index):
    return ' '.join([index_to_word[word] for word in x_train[index]])


In [35]:
print(get_line(0),y_train[0])
print(get_line(1),y_train[1])
print(get_line(2),y_train[2])

the wattie nondiscriminatory mln loss for plc said at only ended said commonwealth could 1 traders now april 0 a after said from 1985 and from foreign 000 april 0 prices its account year a but in this mln home an states earlier and rise and revs vs 000 its 16 vs 000 a but 3 psbr oils several and shareholders and dividend vs 000 its all 4 vs 000 1 mln agreed largely april 0 are 2 states will billion total and against 000 pct dlrs 3
the termination payment airport takes 6 visibility geological 3 6 602 begin up said fully bank expects commodity total is giant a recreation this takes leroy series termination payment airport mln a for capital 1 pre 50 american east said in council takes leroy recommend's france a but u any 4 s 1st losses pct dlrs 4
the lt dlrs demand 000 reuter dividend year lt plus billion 04 000 reuter dividend year an worth new vs reuter dlrs warburg on shrs earnings countries new vs reuter 1985 billion vs 2 lt 4 division 000 reuter from go 000 lt plus which mid 000 reut

In [36]:
word_count = lambda sentence : len(sentence) 
longest_seq = max(x_train,key=word_count) 
longest_seq_length = len(longest_seq)
print(longest_seq,longest_seq_length)

[1, 4, 37, 38, 309, 213, 170, 4, 480, 373, 287, 3519, 13, 4, 48, 193, 6157, 7, 11, 1675, 31, 4034, 1115, 506, 399, 48, 193, 105, 462, 821, 589, 193, 831, 589, 193, 821, 589, 193, 831, 589, 193, 1302, 11, 1148, 1624, 957, 61, 957, 61, 928, 47, 928, 47, 2742, 929, 32, 929, 32, 388, 32, 388, 32, 1146, 4594, 2038, 12, 2038, 12, 2098, 70, 2098, 70, 373, 11, 4594, 624, 80, 47, 3958, 47, 3958, 19, 5614, 19, 5614, 122, 63, 3658, 63, 3658, 63, 5201, 63, 5201, 135, 1717, 134, 2885, 134, 2885, 83, 3703, 83, 3703, 1717, 235, 203, 399, 6976, 48, 193, 105, 462, 821, 589, 193, 831, 589, 193, 821, 589, 193, 831, 589, 193, 2781, 1187, 47, 315, 47, 445, 47, 6370, 47, 2012, 100, 19, 1684, 19, 649, 19, 1527, 19, 2084, 4394, 11312, 44, 4443, 44, 1663, 44, 2860, 44, 2860, 162, 19, 2304, 19, 999, 19, 3455, 19, 3455, 135, 489, 61, 5156, 59, 677, 59, 5246, 59, 5246, 153, 413, 44, 1891, 44, 6184, 47, 3958, 47, 3958, 4862, 14645, 19, 628, 19, 445, 4670, 4670, 1641, 413, 19, 677, 19, 315, 4709, 4709, 664, 413, 32

In [37]:
longest_seq_length=100#keeping max longest seq length to 100
padded_seq = keras.preprocessing.sequence.pad_sequences(x_train,longest_seq_length,padding="post")
print(padded_seq)


[[    1 27595 28842 ...     0     0     0]
 [    1  3267   699 ...     0     0     0]
 [   19   758    15 ...    11    17    12]
 ...
 [    1   141  3890 ...     0     0     0]
 [   88  2321    72 ...   364    17    12]
 [  125  2855    21 ...   113    17    12]]


In [38]:
vocab_length = len(index_to_word)+1

print(len(index_to_word))

30979


In [45]:
x_test_padded = keras.preprocessing.sequence.pad_sequences(x_test,longest_seq_length,padding="post")
y_train_cat = keras.utils.to_categorical(y_train)
y_test_cat = keras.utils.to_categorical(y_test)
y_train_cat.shape[1]

46

In [46]:
model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_length,100,input_length=longest_seq_length))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(y_train_cat.shape[1],activation='sigmoid'))
model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 100)          3098000   
_________________________________________________________________
flatten_3 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 46)                460046    
Total params: 3,558,046
Trainable params: 3,558,046
Non-trainable params: 0
_________________________________________________________________


In [47]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [48]:
np.max(padded_seq)


30979

In [50]:
model.fit(padded_seq,y_train_cat,epochs=10,verbose=1,batch_size=500,shuffle=False,validation_data=(x_test_padded,y_test_cat))

Train on 8982 samples, validate on 2246 samples
Epoch 1/10
8982/8982 [==============================] - 1s 107us/step - loss: 0.0812 - accuracy: 0.9810 - val_loss: 0.0714 - val_accuracy: 0.9816
Epoch 2/10
8982/8982 [==============================] - 1s 110us/step - loss: 0.0685 - accuracy: 0.9817 - val_loss: 0.0667 - val_accuracy: 0.9826
Epoch 3/10
8982/8982 [==============================] - 1s 108us/step - loss: 0.0633 - accuracy: 0.9829 - val_loss: 0.0626 - val_accuracy: 0.9836
Epoch 4/10
8982/8982 [==============================] - 1s 113us/step - loss: 0.0593 - accuracy: 0.9837 - val_loss: 0.0599 - val_accuracy: 0.9843
Epoch 5/10
8982/8982 [==============================] - 1s 109us/step - loss: 0.0563 - accuracy: 0.9850 - val_loss: 0.0580 - val_accuracy: 0.9854
Epoch 6/10
8982/8982 [==============================] - 1s 111us/step - loss: 0.0537 - accuracy: 0.9860 - val_loss: 0.0562 - val_accuracy: 0.9860
Epoch 7/10
8982/8982 [==============================] - 1s 107us/step - loss

In [52]:
#Let's predict and eval
test_score = model.evaluate(x_test_padded,y_test_cat)
print(test_score)

2246/2246 [==============================] - 0s 38us/step
[0.04922867750123687, 0.9877753853797913]


In [72]:
def print_data(index,x_test,y_test,model):
    current_test_data = [x_test[index]]
    line = ' '.join([index_to_word[word] for word in current_test_data[0]])
    #print(line)
    print('y_test = '  + str(y_test[index]))
    current_test_data_padded = keras.preprocessing.sequence.pad_sequences(current_test_data,longest_seq_length,padding="post")
    y_test_cat = [keras.utils.to_categorical(y_test[index])]
    y_pred = model.predict(current_test_data_padded)
    #print(y_pred)
    print('y_pred = ' + str(np.argmax(y_pred)))
    return 


#keras.utils.to_categorical(y_test[1])
for i in range(10):
    print_data(i,x_test,y_test,model)


y_test = 3
y_pred = 3
y_test = 10
y_pred = 19
y_test = 1
y_pred = 16
y_test = 4
y_pred = 4
y_test = 4
y_pred = 4
y_test = 3
y_pred = 3
y_test = 3
y_pred = 3
y_test = 3
y_pred = 3
y_test = 3
y_pred = 3
y_test = 3
y_pred = 3
