In [1]:
import numpy as np
import keras 


Using TensorFlow backend.


In [2]:
#Let's prepare test data ... Let's have 15 dataset and each dataset having 3 timestamps and 1 feature to start with
X = list()
Y = list()
features = 1
timestamps = 3
samples = 15

In [3]:
X = [(x+1) for x in range(features*timestamps*samples)]

In [4]:
X = np.array(X).reshape(samples,timestamps,features)

In [5]:
print(X)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [6]:
for x in X:
    Y.append(x.sum())

In [7]:
Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [8]:
# Now data is there....let's create model
model = keras.models.Sequential()
model.add(keras.layers.LSTM(100,activation='relu',input_shape=(timestamps,features)))
model.add(keras.layers.Dense(1))
model.compile(optimizer='adam',loss='mse')
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 100)               40800     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________


In [9]:
history = model.fit(X,Y,epochs=1000,validation_split=0.2,verbose=1,batch_size=5)

Instructions for updating:
Use tf.cast instead.
Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 0s 34ms/step - loss: 3895.2704 - val_loss: 14151.4443
Epoch 2/1000
12/12 [==============================] - 0s 1ms/step - loss: 3728.7370 - val_loss: 13454.7891
Epoch 3/1000
12/12 [==============================] - 0s 1ms/step - loss: 3527.9862 - val_loss: 12683.7061
Epoch 4/1000
12/12 [==============================] - 0s 1ms/step - loss: 3303.0541 - val_loss: 11756.5713
Epoch 5/1000
12/12 [==============================] - 0s 988us/step - loss: 3053.4215 - val_loss: 10599.5771
Epoch 6/1000
12/12 [==============================] - 0s 1ms/step - loss: 2788.9922 - val_loss: 9100.8477
Epoch 7/1000
12/12 [==============================] - 0s 1ms/step - loss: 2331.1280 - val_loss: 7073.6235
Epoch 8/1000
12/12 [==============================] - 0s 1ms/step - loss: 1801.2259 - val_loss: 4480.4766
Epoch 9/1000
12/12 [==============================] -

12/12 [==============================] - 0s 991us/step - loss: 2.4683 - val_loss: 9.3964
Epoch 78/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.3866 - val_loss: 9.3105
Epoch 79/1000
12/12 [==============================] - 0s 973us/step - loss: 2.2675 - val_loss: 10.5764
Epoch 80/1000
12/12 [==============================] - 0s 969us/step - loss: 2.2128 - val_loss: 11.3829
Epoch 81/1000
12/12 [==============================] - 0s 952us/step - loss: 2.1532 - val_loss: 10.5131
Epoch 82/1000
12/12 [==============================] - 0s 841us/step - loss: 2.0665 - val_loss: 10.3439
Epoch 83/1000
12/12 [==============================] - 0s 910us/step - loss: 1.9565 - val_loss: 8.7489
Epoch 84/1000
12/12 [==============================] - 0s 918us/step - loss: 1.9236 - val_loss: 7.4701
Epoch 85/1000
12/12 [==============================] - 0s 819us/step - loss: 1.8617 - val_loss: 7.7636
Epoch 86/1000
12/12 [==============================] - 0s 886us/step - loss: 1.7908 -

12/12 [==============================] - 0s 964us/step - loss: 0.0337 - val_loss: 0.5296
Epoch 157/1000
12/12 [==============================] - 0s 948us/step - loss: 0.0312 - val_loss: 0.5615
Epoch 158/1000
12/12 [==============================] - 0s 923us/step - loss: 0.0293 - val_loss: 0.5682
Epoch 159/1000
12/12 [==============================] - 0s 970us/step - loss: 0.0315 - val_loss: 0.5447
Epoch 160/1000
12/12 [==============================] - 0s 976us/step - loss: 0.0272 - val_loss: 0.5609
Epoch 161/1000
12/12 [==============================] - 0s 841us/step - loss: 0.0262 - val_loss: 0.5877
Epoch 162/1000
12/12 [==============================] - 0s 998us/step - loss: 0.0253 - val_loss: 0.5659
Epoch 163/1000
12/12 [==============================] - 0s 947us/step - loss: 0.0242 - val_loss: 0.5499
Epoch 164/1000
12/12 [==============================] - 0s 993us/step - loss: 0.0229 - val_loss: 0.5238
Epoch 165/1000
12/12 [==============================] - 0s 899us/step - loss: 0

Epoch 236/1000
12/12 [==============================] - 0s 957us/step - loss: 0.0030 - val_loss: 0.3142
Epoch 237/1000
12/12 [==============================] - 0s 994us/step - loss: 0.0050 - val_loss: 0.3140
Epoch 238/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0037 - val_loss: 0.4297
Epoch 239/1000
12/12 [==============================] - 0s 793us/step - loss: 0.0037 - val_loss: 0.4705
Epoch 240/1000
12/12 [==============================] - 0s 929us/step - loss: 0.0038 - val_loss: 0.3885
Epoch 241/1000
12/12 [==============================] - 0s 954us/step - loss: 0.0043 - val_loss: 0.2854
Epoch 242/1000
12/12 [==============================] - 0s 899us/step - loss: 0.0047 - val_loss: 0.3454
Epoch 243/1000
12/12 [==============================] - 0s 829us/step - loss: 0.0026 - val_loss: 0.4172
Epoch 244/1000
12/12 [==============================] - 0s 941us/step - loss: 0.0029 - val_loss: 0.3917
Epoch 245/1000
12/12 [==============================] - 0s 904us/s

12/12 [==============================] - 0s 964us/step - loss: 8.1951e-04 - val_loss: 0.2127
Epoch 315/1000
12/12 [==============================] - 0s 944us/step - loss: 7.2644e-04 - val_loss: 0.2091
Epoch 316/1000
12/12 [==============================] - 0s 964us/step - loss: 7.3590e-04 - val_loss: 0.1863
Epoch 317/1000
12/12 [==============================] - 0s 984us/step - loss: 9.2071e-04 - val_loss: 0.2019
Epoch 318/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.1878e-04 - val_loss: 0.2357
Epoch 319/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0010 - val_loss: 0.2343
Epoch 320/1000
12/12 [==============================] - 0s 932us/step - loss: 7.0183e-04 - val_loss: 0.1924
Epoch 321/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.0060e-04 - val_loss: 0.1730
Epoch 322/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.8054e-04 - val_loss: 0.2022
Epoch 323/1000
12/12 [==============================] -

12/12 [==============================] - 0s 968us/step - loss: 3.2883e-04 - val_loss: 0.1821
Epoch 392/1000
12/12 [==============================] - 0s 994us/step - loss: 0.0016 - val_loss: 0.1459
Epoch 393/1000
12/12 [==============================] - 0s 973us/step - loss: 4.4079e-04 - val_loss: 0.1094
Epoch 394/1000
12/12 [==============================] - 0s 1ms/step - loss: 6.9274e-04 - val_loss: 0.1413
Epoch 395/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.6901e-04 - val_loss: 0.1686
Epoch 396/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.3169e-04 - val_loss: 0.1365
Epoch 397/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.1337e-04 - val_loss: 0.1204
Epoch 398/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.1591e-04 - val_loss: 0.1459
Epoch 399/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.8956e-04 - val_loss: 0.1422
Epoch 400/1000
12/12 [==============================] - 0s 

12/12 [==============================] - 0s 968us/step - loss: 1.9482e-04 - val_loss: 0.1011
Epoch 469/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.9171e-04 - val_loss: 0.0998
Epoch 470/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.9586e-04 - val_loss: 0.0954
Epoch 471/1000
12/12 [==============================] - 0s 949us/step - loss: 1.8313e-04 - val_loss: 0.1022
Epoch 472/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.0037e-04 - val_loss: 0.0947
Epoch 473/1000
12/12 [==============================] - 0s 945us/step - loss: 2.1679e-04 - val_loss: 0.1015
Epoch 474/1000
12/12 [==============================] - 0s 916us/step - loss: 3.6222e-04 - val_loss: 0.1137
Epoch 475/1000
12/12 [==============================] - 0s 966us/step - loss: 3.8480e-04 - val_loss: 0.0916
Epoch 476/1000
12/12 [==============================] - 0s 885us/step - loss: 2.4807e-04 - val_loss: 0.0945
Epoch 477/1000
12/12 [===========================

Epoch 545/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.4344e-04 - val_loss: 0.0892
Epoch 546/1000
12/12 [==============================] - 0s 915us/step - loss: 1.9783e-04 - val_loss: 0.0661
Epoch 547/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.7944e-04 - val_loss: 0.0731
Epoch 548/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.8954e-05 - val_loss: 0.0846
Epoch 549/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.8404e-04 - val_loss: 0.0719
Epoch 550/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.0869e-04 - val_loss: 0.0730
Epoch 551/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.7529e-05 - val_loss: 0.0763
Epoch 552/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.6978e-05 - val_loss: 0.0784
Epoch 553/1000
12/12 [==============================] - 0s 893us/step - loss: 1.2536e-04 - val_loss: 0.0714
Epoch 554/1000
12/12 [====================

12/12 [==============================] - 0s 1ms/step - loss: 1.2022e-04 - val_loss: 0.0606
Epoch 622/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.2549e-04 - val_loss: 0.0618
Epoch 623/1000
12/12 [==============================] - 0s 2ms/step - loss: 5.1803e-05 - val_loss: 0.0538
Epoch 624/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.2921e-04 - val_loss: 0.0598
Epoch 625/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.8576e-05 - val_loss: 0.0679
Epoch 626/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.1955e-04 - val_loss: 0.0536
Epoch 627/1000
12/12 [==============================] - 0s 2ms/step - loss: 9.7258e-05 - val_loss: 0.0555
Epoch 628/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.4531e-05 - val_loss: 0.0633
Epoch 629/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.4991e-05 - val_loss: 0.0577
Epoch 630/1000
12/12 [==============================] - 0s 1m

12/12 [==============================] - 0s 1ms/step - loss: 3.8677e-05 - val_loss: 0.0496
Epoch 699/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.2557e-05 - val_loss: 0.0444
Epoch 700/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.6329e-04 - val_loss: 0.0438
Epoch 701/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.8705e-04 - val_loss: 0.0634
Epoch 702/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.9278e-04 - val_loss: 0.0357
Epoch 703/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.8775e-04 - val_loss: 0.0476
Epoch 704/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.0089e-05 - val_loss: 0.0654
Epoch 705/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.4499e-04 - val_loss: 0.0365
Epoch 706/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.2619e-04 - val_loss: 0.0467
Epoch 707/1000
12/12 [==============================] - 0s 1m

12/12 [==============================] - 0s 1ms/step - loss: 6.0473e-05 - val_loss: 0.0421
Epoch 776/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.1416e-04 - val_loss: 0.0389
Epoch 777/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.2946e-04 - val_loss: 0.0283
Epoch 778/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.4693e-04 - val_loss: 0.0490
Epoch 779/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.7465e-04 - val_loss: 0.0372
Epoch 780/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.3265e-05 - val_loss: 0.0332
Epoch 781/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.0767e-05 - val_loss: 0.0491
Epoch 782/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.4532e-04 - val_loss: 0.0335
Epoch 783/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.0161e-04 - val_loss: 0.0409
Epoch 784/1000
12/12 [==============================] - 0s 1m

12/12 [==============================] - 0s 1ms/step - loss: 8.4315e-05 - val_loss: 0.0478
Epoch 853/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.3300e-04 - val_loss: 0.0256
Epoch 854/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.8753e-04 - val_loss: 0.0407
Epoch 855/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.5264e-04 - val_loss: 0.0314
Epoch 856/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.2777e-04 - val_loss: 0.0252
Epoch 857/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.0610e-04 - val_loss: 0.0401
Epoch 858/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.4350e-04 - val_loss: 0.0282
Epoch 859/1000
12/12 [==============================] - 0s 1ms/step - loss: 7.5892e-05 - val_loss: 0.0617
Epoch 860/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.1678e-04 - val_loss: 0.0256
Epoch 861/1000
12/12 [==============================] - 0s 1m

12/12 [==============================] - 0s 1ms/step - loss: 1.6221e-05 - val_loss: 0.0315
Epoch 930/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.8556e-05 - val_loss: 0.0324
Epoch 931/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.6817e-05 - val_loss: 0.0306
Epoch 932/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.2826e-05 - val_loss: 0.0308
Epoch 933/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.3909e-05 - val_loss: 0.0325
Epoch 934/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.2353e-05 - val_loss: 0.0262
Epoch 935/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.7659e-05 - val_loss: 0.0344
Epoch 936/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.5296e-05 - val_loss: 0.0254
Epoch 937/1000
12/12 [==============================] - 0s 1ms/step - loss: 6.2730e-05 - val_loss: 0.0312
Epoch 938/1000
12/12 [==============================] - 0s 1m

In [10]:
test_input = np.array([50,51,52])
test_input = test_input.reshape((1, 3, 1))
y_test = test_input.sum()
y_pred = model.predict(test_input, verbose=0)
print(y_test,y_pred)

153 [[152.13235]]


In [11]:
#stacked LSTM
model1 = keras.models.Sequential()
model1.add(keras.layers.LSTM(200,activation='relu',return_sequences=True,input_shape=(timestamps,features)))
model1.add(keras.layers.LSTM(100,activation='relu',return_sequences=True))
model1.add(keras.layers.LSTM(50,activation='relu',return_sequences=True))
model1.add(keras.layers.LSTM(25,activation='relu'))
model1.add(keras.layers.Dense(100,activation='relu'))
model1.add(keras.layers.Dense(50,activation='relu'))
model1.add(keras.layers.Dense(10,activation='relu'))
model1.add(keras.layers.Dense(1))
model1.compile(optimizer='adam',loss='mse')


In [12]:
history = model1.fit(X,Y,epochs=1000,validation_split=0.2,batch_size=5)

Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 3s 213ms/step - loss: 4044.7086 - val_loss: 15172.3877
Epoch 2/1000
12/12 [==============================] - 0s 3ms/step - loss: 4041.6170 - val_loss: 15150.9658
Epoch 3/1000
12/12 [==============================] - 0s 3ms/step - loss: 4034.9170 - val_loss: 15089.7412
Epoch 4/1000
12/12 [==============================] - 0s 3ms/step - loss: 4016.0338 - val_loss: 14871.3818
Epoch 5/1000
12/12 [==============================] - 0s 3ms/step - loss: 3952.6138 - val_loss: 13796.1094
Epoch 6/1000
12/12 [==============================] - 0s 3ms/step - loss: 3710.4414 - val_loss: 10847.6416
Epoch 7/1000
12/12 [==============================] - 0s 3ms/step - loss: 3183.8180 - val_loss: 5416.0181
Epoch 8/1000
12/12 [==============================] - 0s 3ms/step - loss: 1631.6491 - val_loss: 327.5314
Epoch 9/1000
12/12 [==============================] - 0s 3ms/step - loss: 502.6779 - val_loss: 8244.50

12/12 [==============================] - 0s 3ms/step - loss: 0.0232 - val_loss: 0.0043
Epoch 81/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0240 - val_loss: 0.0060
Epoch 82/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0198 - val_loss: 0.0100
Epoch 83/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0163 - val_loss: 0.0105
Epoch 84/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0118 - val_loss: 0.0693
Epoch 85/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0172 - val_loss: 0.0066
Epoch 86/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0132 - val_loss: 0.0028
Epoch 87/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0066 - val_loss: 0.0190
Epoch 88/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0068 - val_loss: 0.0080
Epoch 89/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0091 - val_loss: 0.0120
Epoc

Epoch 159/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.1688e-04 - val_loss: 0.0096
Epoch 160/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.4136e-04 - val_loss: 0.0053
Epoch 161/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.5399e-04 - val_loss: 0.0086
Epoch 162/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.0458e-04 - val_loss: 0.0070
Epoch 163/1000
12/12 [==============================] - 0s 3ms/step - loss: 7.7585e-05 - val_loss: 0.0114
Epoch 164/1000
12/12 [==============================] - 0s 7ms/step - loss: 1.0099e-04 - val_loss: 0.0056
Epoch 165/1000
12/12 [==============================] - 0s 7ms/step - loss: 1.1097e-04 - val_loss: 0.0104
Epoch 166/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.7749e-04 - val_loss: 0.0063
Epoch 167/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.0462e-04 - val_loss: 0.0090
Epoch 168/1000
12/12 [========================

12/12 [==============================] - 0s 4ms/step - loss: 2.4481e-04 - val_loss: 0.0134
Epoch 237/1000
12/12 [==============================] - 0s 4ms/step - loss: 3.6829e-04 - val_loss: 0.0035
Epoch 238/1000
12/12 [==============================] - 0s 4ms/step - loss: 5.9755e-04 - val_loss: 0.0140
Epoch 239/1000
12/12 [==============================] - 0s 4ms/step - loss: 4.1128e-04 - val_loss: 0.0032
Epoch 240/1000
12/12 [==============================] - 0s 4ms/step - loss: 3.3686e-04 - val_loss: 0.0102
Epoch 241/1000
12/12 [==============================] - 0s 4ms/step - loss: 6.2864e-05 - val_loss: 0.0043
Epoch 242/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.1375e-04 - val_loss: 0.0089
Epoch 243/1000
12/12 [==============================] - 0s 4ms/step - loss: 7.4370e-05 - val_loss: 0.0059
Epoch 244/1000
12/12 [==============================] - 0s 4ms/step - loss: 2.9678e-05 - val_loss: 0.0084
Epoch 245/1000
12/12 [==============================] - 0s 4m

12/12 [==============================] - 0s 4ms/step - loss: 0.0345 - val_loss: 0.3046
Epoch 315/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0925 - val_loss: 0.5519
Epoch 316/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0979 - val_loss: 0.5958
Epoch 317/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.1383 - val_loss: 1.5197
Epoch 318/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.4331 - val_loss: 0.2436
Epoch 319/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.2352 - val_loss: 2.1152
Epoch 320/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.4761 - val_loss: 0.4623
Epoch 321/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.3911 - val_loss: 1.3657
Epoch 322/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.5199 - val_loss: 1.8392
Epoch 323/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.6203 - val_loss: 0.

12/12 [==============================] - 0s 4ms/step - loss: 0.0151 - val_loss: 0.0083
Epoch 395/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0110 - val_loss: 0.1109
Epoch 396/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0077 - val_loss: 0.0324
Epoch 397/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0179 - val_loss: 0.2465
Epoch 398/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0446 - val_loss: 0.1302
Epoch 399/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.0170 - val_loss: 0.0594
Epoch 400/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0199 - val_loss: 0.7213
Epoch 401/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0891 - val_loss: 0.2191
Epoch 402/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0862 - val_loss: 0.8067
Epoch 403/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.1098 - val_loss: 0.

12/12 [==============================] - 0s 4ms/step - loss: 1.1705 - val_loss: 0.0559
Epoch 475/1000
12/12 [==============================] - 0s 5ms/step - loss: 1.0651 - val_loss: 5.2040
Epoch 476/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.7572 - val_loss: 0.1061
Epoch 477/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.3634 - val_loss: 0.3960
Epoch 478/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.8083 - val_loss: 2.8040
Epoch 479/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.7137 - val_loss: 0.0188
Epoch 480/1000
12/12 [==============================] - 0s 4ms/step - loss: 2.1804 - val_loss: 0.2998
Epoch 481/1000
12/12 [==============================] - 0s 4ms/step - loss: 2.6052 - val_loss: 5.1422
Epoch 482/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.9101 - val_loss: 32.1824
Epoch 483/1000
12/12 [==============================] - 0s 4ms/step - loss: 5.5688 - val_loss: 1

12/12 [==============================] - 0s 4ms/step - loss: 0.0304 - val_loss: 0.8046
Epoch 555/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.1749 - val_loss: 0.4399
Epoch 556/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0432 - val_loss: 0.3283
Epoch 557/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.1129 - val_loss: 0.8930
Epoch 558/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.1662 - val_loss: 0.1839
Epoch 559/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.1071 - val_loss: 0.2397
Epoch 560/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.1184 - val_loss: 0.0321
Epoch 561/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.0958 - val_loss: 0.0877
Epoch 562/1000
12/12 [==============================] - 0s 5ms/step - loss: 0.0956 - val_loss: 7.9710e-04
Epoch 563/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0503 - val_loss

12/12 [==============================] - 0s 4ms/step - loss: 0.0040 - val_loss: 0.0098
Epoch 635/1000
12/12 [==============================] - 0s 4ms/step - loss: 5.8684e-04 - val_loss: 0.0012
Epoch 636/1000
12/12 [==============================] - 0s 4ms/step - loss: 8.3908e-04 - val_loss: 0.0179
Epoch 637/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0012 - val_loss: 0.0024
Epoch 638/1000
12/12 [==============================] - 0s 4ms/step - loss: 4.0597e-04 - val_loss: 0.0111
Epoch 639/1000
12/12 [==============================] - 0s 4ms/step - loss: 4.5762e-04 - val_loss: 0.0016
Epoch 640/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0011 - val_loss: 0.0137
Epoch 641/1000
12/12 [==============================] - 0s 4ms/step - loss: 6.3201e-04 - val_loss: 0.0089
Epoch 642/1000
12/12 [==============================] - 0s 4ms/step - loss: 5.2331e-04 - val_loss: 0.0049
Epoch 643/1000
12/12 [==============================] - 0s 4ms/step - los

12/12 [==============================] - 0s 4ms/step - loss: 5.5175e-04 - val_loss: 0.0151
Epoch 713/1000
12/12 [==============================] - 0s 4ms/step - loss: 3.1595e-04 - val_loss: 0.0260
Epoch 714/1000
12/12 [==============================] - 0s 4ms/step - loss: 4.1361e-04 - val_loss: 0.0133
Epoch 715/1000
12/12 [==============================] - 0s 4ms/step - loss: 3.1228e-04 - val_loss: 0.0258
Epoch 716/1000
12/12 [==============================] - 0s 4ms/step - loss: 7.2757e-04 - val_loss: 0.0171
Epoch 717/1000
12/12 [==============================] - 0s 4ms/step - loss: 4.8648e-04 - val_loss: 0.0073
Epoch 718/1000
12/12 [==============================] - 0s 4ms/step - loss: 5.3229e-04 - val_loss: 0.0209
Epoch 719/1000
12/12 [==============================] - 0s 4ms/step - loss: 8.8717e-04 - val_loss: 0.0017
Epoch 720/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0015 - val_loss: 0.0150
Epoch 721/1000
12/12 [==============================] - 0s 4ms/st

12/12 [==============================] - 0s 4ms/step - loss: 2.2796 - val_loss: 1.1687
Epoch 792/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.3788 - val_loss: 0.5392
Epoch 793/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.1108 - val_loss: 5.3268
Epoch 794/1000
12/12 [==============================] - 0s 4ms/step - loss: 1.2304 - val_loss: 9.6292
Epoch 795/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.9676 - val_loss: 1.0573
Epoch 796/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.7182 - val_loss: 2.1303
Epoch 797/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.4371 - val_loss: 0.6019
Epoch 798/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0974 - val_loss: 0.0429
Epoch 799/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.1103 - val_loss: 3.3040
Epoch 800/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.2250 - val_loss: 0.

12/12 [==============================] - 0s 4ms/step - loss: 0.0205 - val_loss: 0.0203
Epoch 872/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0167 - val_loss: 0.0544
Epoch 873/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0132 - val_loss: 0.0844
Epoch 874/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0123 - val_loss: 0.0654
Epoch 875/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0220 - val_loss: 0.0912
Epoch 876/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0205 - val_loss: 0.0104
Epoch 877/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0166 - val_loss: 0.3291
Epoch 878/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0222 - val_loss: 0.0082
Epoch 879/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0205 - val_loss: 0.0980
Epoch 880/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0071 - val_loss: 0.

12/12 [==============================] - 0s 4ms/step - loss: 0.0012 - val_loss: 0.0020
Epoch 952/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.0024 - val_loss: 0.0408
Epoch 953/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0016 - val_loss: 0.0064
Epoch 954/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0011 - val_loss: 0.0325
Epoch 955/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0028 - val_loss: 0.0024
Epoch 956/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0031 - val_loss: 0.0267
Epoch 957/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0012 - val_loss: 0.0109
Epoch 958/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0022 - val_loss: 0.0368
Epoch 959/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0033 - val_loss: 0.0022
Epoch 960/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.0045 - val_loss: 0.

In [13]:
y_pred = model1.predict(test_input, verbose=0)
print(y_test,y_pred)

153 [[153.42735]]


In [14]:
#Now trying with bidirectional LSTM
model2 = keras.models.Sequential()
model2.add(keras.layers.Bidirectional(keras.layers.LSTM(50,input_shape=(timestamps,features))))
model2.add(keras.layers.Dense(1))
model2.compile(optimizer='adam',loss='mse')

In [15]:
history = model2.fit(X,Y,epochs=1000,validation_split=0.2,verbose=1,batch_size=5)

Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 2s 126ms/step - loss: 4050.2147 - val_loss: 15152.7314
Epoch 2/1000
12/12 [==============================] - 0s 1ms/step - loss: 4015.6363 - val_loss: 15074.4219
Epoch 3/1000
12/12 [==============================] - 0s 1ms/step - loss: 3980.4644 - val_loss: 14999.6924
Epoch 4/1000
12/12 [==============================] - 0s 1ms/step - loss: 3947.8730 - val_loss: 14929.3174
Epoch 5/1000
12/12 [==============================] - 0s 1ms/step - loss: 3911.8196 - val_loss: 14862.7627
Epoch 6/1000
12/12 [==============================] - 0s 1ms/step - loss: 3880.9984 - val_loss: 14797.2939
Epoch 7/1000
12/12 [==============================] - 0s 1ms/step - loss: 3846.1774 - val_loss: 14730.2393
Epoch 8/1000
12/12 [==============================] - 0s 1ms/step - loss: 3811.3754 - val_loss: 14663.6455
Epoch 9/1000
12/12 [==============================] - 0s 1ms/step - loss: 3781.8958 - val_loss: 145

12/12 [==============================] - 0s 979us/step - loss: 1448.1774 - val_loss: 8331.7188
Epoch 77/1000
12/12 [==============================] - 0s 1ms/step - loss: 1429.1047 - val_loss: 8267.3867
Epoch 78/1000
12/12 [==============================] - 0s 968us/step - loss: 1410.3559 - val_loss: 8201.1729
Epoch 79/1000
12/12 [==============================] - 0s 1ms/step - loss: 1389.4796 - val_loss: 8137.9531
Epoch 80/1000
12/12 [==============================] - 0s 985us/step - loss: 1371.1621 - val_loss: 8077.2007
Epoch 81/1000
12/12 [==============================] - 0s 1ms/step - loss: 1355.5192 - val_loss: 8018.0962
Epoch 82/1000
12/12 [==============================] - 0s 1ms/step - loss: 1336.6214 - val_loss: 7963.8608
Epoch 83/1000
12/12 [==============================] - 0s 1ms/step - loss: 1321.5611 - val_loss: 7910.2124
Epoch 84/1000
12/12 [==============================] - 0s 981us/step - loss: 1307.7110 - val_loss: 7856.6812
Epoch 85/1000
12/12 [======================

12/12 [==============================] - 0s 941us/step - loss: 661.0673 - val_loss: 5412.5542
Epoch 153/1000
12/12 [==============================] - 0s 1ms/step - loss: 655.7943 - val_loss: 5386.2778
Epoch 154/1000
12/12 [==============================] - 0s 956us/step - loss: 649.6456 - val_loss: 5361.7622
Epoch 155/1000
12/12 [==============================] - 0s 1ms/step - loss: 643.8620 - val_loss: 5337.6094
Epoch 156/1000
12/12 [==============================] - 0s 978us/step - loss: 638.8040 - val_loss: 5312.4878
Epoch 157/1000
12/12 [==============================] - 0s 954us/step - loss: 632.7111 - val_loss: 5287.9614
Epoch 158/1000
12/12 [==============================] - 0s 977us/step - loss: 627.7335 - val_loss: 5261.8823
Epoch 159/1000
12/12 [==============================] - 0s 972us/step - loss: 621.2005 - val_loss: 5236.2837
Epoch 160/1000
12/12 [==============================] - 0s 970us/step - loss: 616.4156 - val_loss: 5209.0454
Epoch 161/1000
12/12 [================

Epoch 228/1000
12/12 [==============================] - 0s 1ms/step - loss: 329.3946 - val_loss: 3762.5286
Epoch 229/1000
12/12 [==============================] - 0s 934us/step - loss: 327.3564 - val_loss: 3743.4626
Epoch 230/1000
12/12 [==============================] - 0s 978us/step - loss: 323.5116 - val_loss: 3725.9285
Epoch 231/1000
12/12 [==============================] - 0s 922us/step - loss: 321.1981 - val_loss: 3707.2881
Epoch 232/1000
12/12 [==============================] - 0s 957us/step - loss: 318.1759 - val_loss: 3689.7346
Epoch 233/1000
12/12 [==============================] - 0s 928us/step - loss: 314.5551 - val_loss: 3673.8010
Epoch 234/1000
12/12 [==============================] - 0s 960us/step - loss: 312.0090 - val_loss: 3657.3359
Epoch 235/1000
12/12 [==============================] - 0s 945us/step - loss: 309.2883 - val_loss: 3641.1965
Epoch 236/1000
12/12 [==============================] - 0s 928us/step - loss: 306.5258 - val_loss: 3625.7051
Epoch 237/1000
12/12 

12/12 [==============================] - 0s 980us/step - loss: 177.1253 - val_loss: 2761.1667
Epoch 304/1000
12/12 [==============================] - 0s 1ms/step - loss: 175.4367 - val_loss: 2750.7415
Epoch 305/1000
12/12 [==============================] - 0s 1ms/step - loss: 173.9165 - val_loss: 2741.0232
Epoch 306/1000
12/12 [==============================] - 0s 984us/step - loss: 172.3859 - val_loss: 2731.2273
Epoch 307/1000
12/12 [==============================] - 0s 1ms/step - loss: 171.3943 - val_loss: 2719.4221
Epoch 308/1000
12/12 [==============================] - 0s 1ms/step - loss: 170.0674 - val_loss: 2708.1882
Epoch 309/1000
12/12 [==============================] - 0s 909us/step - loss: 168.3479 - val_loss: 2698.1306
Epoch 310/1000
12/12 [==============================] - 0s 1ms/step - loss: 167.3044 - val_loss: 2688.0723
Epoch 311/1000
12/12 [==============================] - 0s 982us/step - loss: 165.8540 - val_loss: 2678.7471
Epoch 312/1000
12/12 [======================

12/12 [==============================] - 0s 2ms/step - loss: 94.2442 - val_loss: 2058.3792
Epoch 380/1000
12/12 [==============================] - 0s 1ms/step - loss: 93.3811 - val_loss: 2052.0293
Epoch 381/1000
12/12 [==============================] - 0s 2ms/step - loss: 92.7251 - val_loss: 2045.5850
Epoch 382/1000
12/12 [==============================] - 0s 1ms/step - loss: 92.2234 - val_loss: 2038.5664
Epoch 383/1000
12/12 [==============================] - 0s 1ms/step - loss: 91.3692 - val_loss: 2032.1385
Epoch 384/1000
12/12 [==============================] - 0s 2ms/step - loss: 90.7844 - val_loss: 2025.8746
Epoch 385/1000
12/12 [==============================] - 0s 1ms/step - loss: 90.1465 - val_loss: 2019.7264
Epoch 386/1000
12/12 [==============================] - 0s 1ms/step - loss: 89.5128 - val_loss: 2013.3861
Epoch 387/1000
12/12 [==============================] - 0s 1ms/step - loss: 88.8141 - val_loss: 2006.4215
Epoch 388/1000
12/12 [==============================] - 0s 2m

12/12 [==============================] - 0s 1ms/step - loss: 52.7539 - val_loss: 1599.6591
Epoch 457/1000
12/12 [==============================] - 0s 2ms/step - loss: 52.3530 - val_loss: 1595.1274
Epoch 458/1000
12/12 [==============================] - 0s 1ms/step - loss: 51.9968 - val_loss: 1590.8131
Epoch 459/1000
12/12 [==============================] - 0s 2ms/step - loss: 51.6562 - val_loss: 1586.4775
Epoch 460/1000
12/12 [==============================] - 0s 2ms/step - loss: 51.2918 - val_loss: 1581.6226
Epoch 461/1000
12/12 [==============================] - 0s 2ms/step - loss: 50.9607 - val_loss: 1576.8467
Epoch 462/1000
12/12 [==============================] - 0s 2ms/step - loss: 50.6489 - val_loss: 1572.0087
Epoch 463/1000
12/12 [==============================] - 0s 2ms/step - loss: 50.2337 - val_loss: 1567.4897
Epoch 464/1000
12/12 [==============================] - 0s 2ms/step - loss: 49.8765 - val_loss: 1563.2233
Epoch 465/1000
12/12 [==============================] - 0s 1m

12/12 [==============================] - 0s 2ms/step - loss: 30.2609 - val_loss: 1278.3860
Epoch 534/1000
12/12 [==============================] - 0s 2ms/step - loss: 29.9803 - val_loss: 1275.0157
Epoch 535/1000
12/12 [==============================] - 0s 2ms/step - loss: 29.7667 - val_loss: 1271.7133
Epoch 536/1000
12/12 [==============================] - 0s 2ms/step - loss: 29.5856 - val_loss: 1268.5983
Epoch 537/1000
12/12 [==============================] - 0s 2ms/step - loss: 29.3924 - val_loss: 1265.5565
Epoch 538/1000
12/12 [==============================] - 0s 2ms/step - loss: 29.2252 - val_loss: 1262.1968
Epoch 539/1000
12/12 [==============================] - 0s 2ms/step - loss: 28.9256 - val_loss: 1259.0165
Epoch 540/1000
12/12 [==============================] - 0s 2ms/step - loss: 28.8446 - val_loss: 1255.0817
Epoch 541/1000
12/12 [==============================] - 0s 2ms/step - loss: 28.5553 - val_loss: 1251.7172
Epoch 542/1000
12/12 [==============================] - 0s 2m

12/12 [==============================] - 0s 2ms/step - loss: 17.7044 - val_loss: 1049.1904
Epoch 611/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.5925 - val_loss: 1046.3326
Epoch 612/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.4958 - val_loss: 1043.2056
Epoch 613/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.3949 - val_loss: 1040.2875
Epoch 614/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.2290 - val_loss: 1037.8209
Epoch 615/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.1245 - val_loss: 1035.3512
Epoch 616/1000
12/12 [==============================] - 0s 2ms/step - loss: 17.0031 - val_loss: 1032.9633
Epoch 617/1000
12/12 [==============================] - 0s 2ms/step - loss: 16.8266 - val_loss: 1030.5121
Epoch 618/1000
12/12 [==============================] - 0s 2ms/step - loss: 16.7942 - val_loss: 1027.5667
Epoch 619/1000
12/12 [==============================] - 0s 2m

Epoch 688/1000
12/12 [==============================] - 0s 2ms/step - loss: 10.2992 - val_loss: 872.5264
Epoch 689/1000
12/12 [==============================] - 0s 1ms/step - loss: 10.2544 - val_loss: 870.6570
Epoch 690/1000
12/12 [==============================] - 0s 2ms/step - loss: 10.1504 - val_loss: 868.6414
Epoch 691/1000
12/12 [==============================] - 0s 1ms/step - loss: 10.0971 - val_loss: 866.6281
Epoch 692/1000
12/12 [==============================] - 0s 1ms/step - loss: 10.0269 - val_loss: 864.1804
Epoch 693/1000
12/12 [==============================] - 0s 2ms/step - loss: 9.8466 - val_loss: 861.4670
Epoch 694/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.7983 - val_loss: 858.6826
Epoch 695/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.7396 - val_loss: 856.1611
Epoch 696/1000
12/12 [==============================] - 0s 2ms/step - loss: 9.7197 - val_loss: 853.4684
Epoch 697/1000
12/12 [==============================] - 0s 

12/12 [==============================] - 0s 2ms/step - loss: 6.0974 - val_loss: 744.5239
Epoch 767/1000
12/12 [==============================] - 0s 2ms/step - loss: 6.0688 - val_loss: 742.9751
Epoch 768/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.9895 - val_loss: 741.6362
Epoch 769/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.9988 - val_loss: 740.3784
Epoch 770/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.9792 - val_loss: 739.0459
Epoch 771/1000
12/12 [==============================] - 0s 2ms/step - loss: 5.8977 - val_loss: 737.7751
Epoch 772/1000
12/12 [==============================] - 0s 2ms/step - loss: 5.8785 - val_loss: 736.5511
Epoch 773/1000
12/12 [==============================] - 0s 2ms/step - loss: 5.8569 - val_loss: 735.4465
Epoch 774/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.7952 - val_loss: 734.4749
Epoch 775/1000
12/12 [==============================] - 0s 2ms/step - loss: 5.8

Epoch 845/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.7703 - val_loss: 651.0427
Epoch 846/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.7631 - val_loss: 649.7303
Epoch 847/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.7417 - val_loss: 648.5239
Epoch 848/1000
12/12 [==============================] - 0s 2ms/step - loss: 3.7029 - val_loss: 647.5637
Epoch 849/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.6815 - val_loss: 646.5443
Epoch 850/1000
12/12 [==============================] - 0s 2ms/step - loss: 3.6413 - val_loss: 645.5579
Epoch 851/1000
12/12 [==============================] - 0s 2ms/step - loss: 3.6382 - val_loss: 644.3521
Epoch 852/1000
12/12 [==============================] - 0s 1ms/step - loss: 3.6057 - val_loss: 643.3381
Epoch 853/1000
12/12 [==============================] - 0s 2ms/step - loss: 3.6200 - val_loss: 642.3359
Epoch 854/1000
12/12 [==============================] - 0s 1ms/s

Epoch 924/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.3797 - val_loss: 577.7141
Epoch 925/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.3492 - val_loss: 576.9622
Epoch 926/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.3476 - val_loss: 575.9007
Epoch 927/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.3193 - val_loss: 575.0599
Epoch 928/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.3070 - val_loss: 574.2641
Epoch 929/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.2832 - val_loss: 573.5461
Epoch 930/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.2889 - val_loss: 572.8627
Epoch 931/1000
12/12 [==============================] - 0s 2ms/step - loss: 2.2635 - val_loss: 572.1680
Epoch 932/1000
12/12 [==============================] - 0s 1ms/step - loss: 2.2505 - val_loss: 571.4882
Epoch 933/1000
12/12 [==============================] - 0s 2ms/s

In [16]:
y_pred = model1.predict(test_input, verbose=0)
print(y_test,y_pred)

153 [[153.42735]]
