In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.contrib import rnn
import random
import collections
import os
import time
import pandas as pd
from keras.preprocessing.text import Tokenizer
import keras


Using TensorFlow backend.


In [2]:
path_to_file = 'machinelearninglstm.txt'
with open(path_to_file) as f:
    text = f.readlines()
    

In [3]:
text 


['Machine learning models take vectors (arrays of numbers) as input. When working with text, the first thing we must do come up with a strategy to convert strings to numbers (or to "vectorize" the text) before feeding it to the model. In this section, we will look at three strategies for doing so.\n',
 '\n',
 'One-hot encodings\n',
 'As a first idea, we might "one-hot" encode each word in our vocabulary. Consider the sentence "The cat sat on the mat". The vocabulary (or unique words) in this sentence is (cat, mat, on, sat, the). To represent each word, we will create a zero vector with length equal to the vocabulary, then place a one in the index that corresponds to the word. This approach is shown in the following diagram.\n',
 '\n',
 'content from https://www.tensorflow.org/tutorials/text/word_embeddings']

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)
dataset = tokenizer.texts_to_sequences(text)


In [5]:
print(tokenizer.word_index)
print(dataset)


{'when': 33, 'words': 63, 'following': 77, 'with': 7, 'shown': 76, 'model': 47, 'this': 9, 'three': 51, 'tutorials': 85, 'do': 37, 'mat': 23, 'might': 58, 'sat': 21, 'up': 39, 'strings': 42, 'before': 44, 'it': 46, 'convert': 41, 'of': 31, 'models': 27, 'as': 13, 'create': 65, 'then': 70, 'working': 34, 'to': 2, 'encodings': 56, 'approach': 75, 'will': 16, 'tensorflow': 83, 'numbers': 12, 'take': 28, 'zero': 66, 'vectorize': 43, 'a': 5, 'equal': 69, 'embeddings': 86, 'each': 18, 'encode': 59, 'corresponds': 74, 'at': 50, 'learning': 26, 'look': 49, 'www': 82, 'vector': 67, 'hot': 17, 'strategies': 52, 'from': 80, 'strategy': 40, 'first': 14, 'arrays': 30, 'vocabulary': 11, 'org': 84, 'come': 38, 'that': 73, 'place': 71, 'vectors': 29, 'text': 8, 'must': 36, 'length': 68, 'represent': 64, 'index': 72, 'for': 53, 'in': 3, 'we': 4, 'doing': 54, 'idea': 57, 'so': 55, 'sentence': 19, 'unique': 62, 'or': 15, 'input': 32, 'one': 10, 'word': 6, 'diagram': 78, 'content': 79, 'cat': 20, 'https':

In [6]:

def convert2DStrTo1DStr(dataset):
    out = []
    for x in dataset:
        for y in x:        
            out.append(y)
    return out
print(convert2DStrTo1DStr(dataset))


[25, 26, 27, 28, 29, 30, 31, 12, 13, 32, 33, 34, 7, 8, 1, 14, 35, 4, 36, 37, 38, 39, 7, 5, 40, 2, 41, 42, 2, 12, 15, 2, 43, 1, 8, 44, 45, 46, 2, 1, 47, 3, 9, 48, 4, 16, 49, 50, 51, 52, 53, 54, 55, 10, 17, 56, 13, 5, 14, 57, 4, 58, 10, 17, 59, 18, 6, 3, 60, 11, 61, 1, 19, 1, 20, 21, 22, 1, 23, 1, 11, 15, 62, 63, 3, 9, 19, 24, 20, 23, 22, 21, 1, 2, 64, 18, 6, 4, 16, 65, 5, 66, 67, 7, 68, 69, 2, 1, 11, 70, 71, 5, 10, 3, 1, 72, 73, 74, 2, 1, 6, 9, 75, 24, 76, 3, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85, 8, 6, 86]


In [7]:
encoded = convert2DStrTo1DStr(dataset)


In [8]:
vocab_size = len(tokenizer.word_index)+1
print('Vocabulary Size: %d' % vocab_size)


Vocabulary Size: 87


In [9]:
sequences = list()
seq_length = 3
x_data = []
y_data = []
for i in range(0, len(encoded)-seq_length):
    in_seq = encoded[i:i+seq_length]
    out_seq= encoded[i+seq_length]
    x_data.append(in_seq)
    y_data.append(out_seq)


In [10]:
print('Total Sequences: %d' % len(y_data))


Total Sequences: 136


In [11]:
print(x_data[0],y_data[0])


[25, 26, 27] 28


In [12]:
X = np.array(x_data)
X = np.array(X).reshape(len(x_data),seq_length,1)
print(X.shape, X)


(136, 3, 1) [[[25]
  [26]
  [27]]

 [[26]
  [27]
  [28]]

 [[27]
  [28]
  [29]]

 [[28]
  [29]
  [30]]

 [[29]
  [30]
  [31]]

 [[30]
  [31]
  [12]]

 [[31]
  [12]
  [13]]

 [[12]
  [13]
  [32]]

 [[13]
  [32]
  [33]]

 [[32]
  [33]
  [34]]

 [[33]
  [34]
  [ 7]]

 [[34]
  [ 7]
  [ 8]]

 [[ 7]
  [ 8]
  [ 1]]

 [[ 8]
  [ 1]
  [14]]

 [[ 1]
  [14]
  [35]]

 [[14]
  [35]
  [ 4]]

 [[35]
  [ 4]
  [36]]

 [[ 4]
  [36]
  [37]]

 [[36]
  [37]
  [38]]

 [[37]
  [38]
  [39]]

 [[38]
  [39]
  [ 7]]

 [[39]
  [ 7]
  [ 5]]

 [[ 7]
  [ 5]
  [40]]

 [[ 5]
  [40]
  [ 2]]

 [[40]
  [ 2]
  [41]]

 [[ 2]
  [41]
  [42]]

 [[41]
  [42]
  [ 2]]

 [[42]
  [ 2]
  [12]]

 [[ 2]
  [12]
  [15]]

 [[12]
  [15]
  [ 2]]

 [[15]
  [ 2]
  [43]]

 [[ 2]
  [43]
  [ 1]]

 [[43]
  [ 1]
  [ 8]]

 [[ 1]
  [ 8]
  [44]]

 [[ 8]
  [44]
  [45]]

 [[44]
  [45]
  [46]]

 [[45]
  [46]
  [ 2]]

 [[46]
  [ 2]
  [ 1]]

 [[ 2]
  [ 1]
  [47]]

 [[ 1]
  [47]
  [ 3]]

 [[47]
  [ 3]
  [ 9]]

 [[ 3]
  [ 9]
  [48]]

 [[ 9]
  [48]
  [ 4]]


In [13]:
Y = np.array(y_data)
Y_cat = keras.utils.to_categorical(Y)
Y_cat.shape


(136, 87)

In [14]:
model = keras.models.Sequential()
model.add(keras.layers.LSTM(200,input_shape=(seq_length,1)))
model.add(keras.layers.Dense(Y_cat.shape[1],activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 200)               161600    
_________________________________________________________________
dense_1 (Dense)              (None, 87)                17487     
Total params: 179,087
Trainable params: 179,087
Non-trainable params: 0
_________________________________________________________________
None


In [15]:
model.fit(X,Y_cat,epochs=500,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 0s - loss: 4.5884 - accuracy: 0.0000e+00
Epoch 2/500
 - 0s - loss: 4.3659 - accuracy: 0.0809
Epoch 3/500
 - 0s - loss: 4.2367 - accuracy: 0.1103
Epoch 4/500
 - 0s - loss: 4.1337 - accuracy: 0.1029
Epoch 5/500
 - 0s - loss: 4.0670 - accuracy: 0.1029
Epoch 6/500
 - 0s - loss: 4.0026 - accuracy: 0.1103
Epoch 7/500
 - 0s - loss: 3.9554 - accuracy: 0.1103
Epoch 8/500
 - 0s - loss: 3.9081 - accuracy: 0.1103
Epoch 9/500
 - 0s - loss: 3.8633 - accuracy: 0.1103
Epoch 10/500
 - 0s - loss: 3.8128 - accuracy: 0.1103
Epoch 11/500
 - 0s - loss: 3.7554 - accuracy: 0.1103
Epoch 12/500
 - 0s - loss: 3.7029 - accuracy: 0.1176
Epoch 13/500
 - 0s - loss: 3.6471 - accuracy: 0.1103
Epoch 14/500
 - 0s - loss: 3.5853 - accuracy: 0.1029
Epoch 15/500
 - 0s - loss: 3.5184 - accuracy: 0.1103
Epoch 16/500
 - 0s - loss: 3.4543 - accuracy: 0.1176
Epoch 17/500
 - 0s - loss: 3.3934 - accuracy: 0.1250
Epoch 18/500
 - 0s - loss: 3.3320 - accuracy: 0.1397
Epo

Epoch 150/500
 - 0s - loss: 0.7611 - accuracy: 0.8309
Epoch 151/500
 - 0s - loss: 0.7592 - accuracy: 0.8309
Epoch 152/500
 - 0s - loss: 0.7559 - accuracy: 0.7868
Epoch 153/500
 - 0s - loss: 0.7616 - accuracy: 0.7941
Epoch 154/500
 - 0s - loss: 0.7491 - accuracy: 0.8309
Epoch 155/500
 - 0s - loss: 0.7384 - accuracy: 0.8235
Epoch 156/500
 - 0s - loss: 0.7354 - accuracy: 0.8088
Epoch 157/500
 - 0s - loss: 0.7312 - accuracy: 0.8235
Epoch 158/500
 - 0s - loss: 0.7300 - accuracy: 0.8088
Epoch 159/500
 - 0s - loss: 0.7250 - accuracy: 0.8162
Epoch 160/500
 - 0s - loss: 0.7267 - accuracy: 0.8088
Epoch 161/500
 - 0s - loss: 0.7190 - accuracy: 0.8162
Epoch 162/500
 - 0s - loss: 0.7217 - accuracy: 0.8088
Epoch 163/500
 - 0s - loss: 0.7081 - accuracy: 0.8309
Epoch 164/500
 - 0s - loss: 0.7043 - accuracy: 0.8015
Epoch 165/500
 - 0s - loss: 0.7031 - accuracy: 0.7941
Epoch 166/500
 - 0s - loss: 0.7011 - accuracy: 0.8088
Epoch 167/500
 - 0s - loss: 0.7047 - accuracy: 0.7868
Epoch 168/500
 - 0s - loss: 

Epoch 302/500
 - 0s - loss: 0.4154 - accuracy: 0.8676
Epoch 303/500
 - 0s - loss: 0.4183 - accuracy: 0.8750
Epoch 304/500
 - 0s - loss: 0.4116 - accuracy: 0.8824
Epoch 305/500
 - 0s - loss: 0.4127 - accuracy: 0.8897
Epoch 306/500
 - 0s - loss: 0.4148 - accuracy: 0.8676
Epoch 307/500
 - 0s - loss: 0.4063 - accuracy: 0.8897
Epoch 308/500
 - 0s - loss: 0.4034 - accuracy: 0.9044
Epoch 309/500
 - 0s - loss: 0.4022 - accuracy: 0.8897
Epoch 310/500
 - 0s - loss: 0.4038 - accuracy: 0.8897
Epoch 311/500
 - 0s - loss: 0.4079 - accuracy: 0.8897
Epoch 312/500
 - 0s - loss: 0.4028 - accuracy: 0.8897
Epoch 313/500
 - 0s - loss: 0.3964 - accuracy: 0.8824
Epoch 314/500
 - 0s - loss: 0.4256 - accuracy: 0.8603
Epoch 315/500
 - 0s - loss: 0.4039 - accuracy: 0.8824
Epoch 316/500
 - 0s - loss: 0.4172 - accuracy: 0.8529
Epoch 317/500
 - 0s - loss: 0.4142 - accuracy: 0.8529
Epoch 318/500
 - 0s - loss: 0.4171 - accuracy: 0.8603
Epoch 319/500
 - 0s - loss: 0.4028 - accuracy: 0.8529
Epoch 320/500
 - 0s - loss: 

Epoch 454/500
 - 0s - loss: 0.3315 - accuracy: 0.8971
Epoch 455/500
 - 0s - loss: 0.3097 - accuracy: 0.8971
Epoch 456/500
 - 0s - loss: 0.3086 - accuracy: 0.8897
Epoch 457/500
 - 0s - loss: 0.3119 - accuracy: 0.8971
Epoch 458/500
 - 0s - loss: 0.3191 - accuracy: 0.8676
Epoch 459/500
 - 0s - loss: 0.3098 - accuracy: 0.8824
Epoch 460/500
 - 0s - loss: 0.3006 - accuracy: 0.9118
Epoch 461/500
 - 0s - loss: 0.2971 - accuracy: 0.9191
Epoch 462/500
 - 0s - loss: 0.2968 - accuracy: 0.9265
Epoch 463/500
 - 0s - loss: 0.3140 - accuracy: 0.8750
Epoch 464/500
 - 0s - loss: 0.3051 - accuracy: 0.8971
Epoch 465/500
 - 0s - loss: 0.2952 - accuracy: 0.9044
Epoch 466/500
 - 0s - loss: 0.3039 - accuracy: 0.8971
Epoch 467/500
 - 0s - loss: 0.2999 - accuracy: 0.8971
Epoch 468/500
 - 0s - loss: 0.2961 - accuracy: 0.9118
Epoch 469/500
 - 0s - loss: 0.2924 - accuracy: 0.9118
Epoch 470/500
 - 0s - loss: 0.2905 - accuracy: 0.9265
Epoch 471/500
 - 0s - loss: 0.2894 - accuracy: 0.9118
Epoch 472/500
 - 0s - loss: 

In [16]:
def predict(current_words,tokenizer,model):
    encoded_input = np.array(tokenizer.texts_to_sequences([current_words])[0])
    if(len(encoded_input)>seq_length):
        encoded_input = encoded_input[-seq_length:]
    encoded_input = np.array(encoded_input).reshape(1,seq_length,1)#assuming current_words are only 3 words
    y_class = model.predict_classes(encoded_input)
    for word,index in tokenizer.word_index.items():
        if index==y_class:
            out_word = word
            break
    return word
def predict_n(current_words,tokenizer,model,n):
    next_words = current_words
    out = current_words
    for i in range(n):
        next_word = predict(out,tokenizer,model)
        out = out +' ' +  next_word
    return out


In [17]:
predict('working with text',tokenizer,model)

'the'

In [18]:
print(predict_n('working with text',tokenizer,model,10))

working with text the first thing we must do come up up up
